<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>EhGalleryDownloader</AssemblyName>
    <RootNamespace>EhGalleryDownloader</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <DebugType>embedded</DebugType>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup Condition="Exists('tools\gallery-dl.exe')">
    <Content Include="tools\gallery-dl.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="Exists('THIRD-PARTY-NOTICES.txt')">
    <Content Include="THIRD-PARTY-NOTICES.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <None Remove="Tests\**\*" />
  </ItemGroup>
</Project>
